### ISSUE TITLE
Firebase Login

### ISSUE THREAD

**Issue by martyh888** [laqul/laqul#10]
I have got everything working except for the firebase connection.

After logging in I am not being redirected to the dashboard automatically and need to refresh.

I am getting an issue with the token call verifyCustomToken?key=FIREBASE_API_KEY

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "INVALID_CUSTOM_TOKEN : AUDIENCE_MISMATCH"
   }
  ],
  "code": 400,
  "message": "INVALID_CUSTOM_TOKEN : AUDIENCE_MISMATCH"
 }
}

Any suggestions to why?

**Comment by laqul** [comment]
You downloaded the private key from firebase?

**Comment by laqul** [comment]
Download the private key from firebase and rename it to firebase-private.key and paste it to api/storage folder.

Steps for generate private key: [Link](https://firebase.google.com/docs/auth/web/custom-auth)

**Comment by martyh888** [comment]
finally got it to work by stripping out the no private key information. It wasn't just to download the JSON Private Key and rename but also strip it down to just the text only with ----PRIVATE KEY...... and remove the \n and replace with line breaks. It now works. But still, need to implement the identifier and provider data being registered on the firebase authentications but I guess this is more addon options. Thanks, great work
