### ISSUE TITLE
Fresh install gives 504 on proxy to /backend

### ISSUE THREAD

**Issue by mandofever78** [laqul/laqul#12]
Had this issue upon fresh install and found the fix [in this comment.] Credit: @jonhhamm (https://github.com/webpack/webpack-dev-server/issues/424#issuecomment-271458094)

> PHP standalone server requires "[::1]" instead of localhost:

```
proxy: {
        '/backend': {
          target: 'http://[::1]:8001', 
          changeOrigin: true,
          pathRewrite: {
            '^/backend': ''
          }
        }
      }
```

**Comment by laqul** [comment]
@mandofever78 thanks for the fix, in my development environment I don't have this issue
