### ISSUE TITLE
clientId and clientSecret inside client-backend

### ISSUE THREAD

**Issue by 123mitnik** [laqul/laqul#14]
inside client-backend

what are these 

protected $clientId = '71d4f8ea-1138-11e8-a472-002163944a0x';
protected $clientSecret = 'y1d4f8ea113811e8a472002163944a0x1234';

**Comment by laqul** [comment]
@123mitnik clientId and clientSecret is the default credentials setup in the API (laqul/api/database/seeds/OauthClientSeeder.php), you can change it.
